### ISSUE TITLE
Voice commands going through cloud instead of local fulfillment; error when forced local

### ISSUE THREAD

**Issue by benrafshoon** [NabuCasa/home-assistant-google-assistant-local-sdk#32] opened 2022-12-30 02:36 UTC
Home Assistant version 2022.12.8
app.js version 2.1.6

Voice commands for my Google Home Mini are not going through the local path. When I go to the console for my Google Home Mini, I see successful IDENTIFY and REACHABLE_DEVICES calls, and I can see the corresponding "Responding to local message:" log entries on the Home Assistant side. But when I go to turn on a light, I don't see any EXECUTE calls on the Google Home Mini. Additionally, if I run "Hey Google, force local", and try to turn on a light, I get "Sorry, it looks like kitchen isn't available right now". 

Google Home Mini logs
<img width="1202" alt="Screenshot 2022-12-29 at 6 29 49 PM" src="https://user-images.githubusercontent.com/2784952/210028628-daaec8b0-9cd0-44c4-acb3-6b5dbb010d98.png">
All the entries after the screenshot are successful REACHABLE_DEVICES calls.

I don't see any error logs in the Google Cloud logs for my Actions on Google project.

What I'm seeing sounds somewhat similar to https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/issues/20

**Comment by balloob** [comment] 2022-12-30 03:53
Duplicate of #28

**Closed as completed by balloob** 2022-12-30 03:53 UTC
